"use strict";

const START_YEAR    = 2015;
const END_YEAR      = 2017;

const MODE_INITFUNDBASE = 0;
const MODE_INITFUNDARCH = 1;
const MODE_UPDFUNDARCH  = 2;

exports.START_YEAR = START_YEAR;
exports.END_YEAR = END_YEAR;

exports.MODE_INITFUNDBASE = MODE_INITFUNDBASE;
exports.MODE_INITFUNDARCH = MODE_INITFUNDARCH;
exports.MODE_UPDFUNDARCH = MODE_UPDFUNDARCH;